# Generated by Django 4.2.2 on 2023-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=200)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile pic')),
            ],
        ),
    ]
