# Generated by Django 4.2.2 on 2023-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone_no', models.IntegerField()),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('about', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('profilepic1', models.ImageField(upload_to='small icon')),
                ('address', models.TextField(blank=True, null=True)),
                ('years_exp', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=250)),
                ('starting_year', models.PositiveIntegerField()),
                ('ending_year', models.PositiveIntegerField()),
                ('university', models.CharField(max_length=500)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('pro_type', models.CharField(max_length=100)),
                ('project_pic', models.ImageField(upload_to='project icon')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('about_service', models.TextField()),
                ('service_pic', models.ImageField(blank=True, null=True, upload_to='service Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_per', models.IntegerField()),
            ],
        ),
    ]
