# Generated by Django 4.2.2 on 2023-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0002_aboutpage_education_projects_services_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='profilepic1',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
