# Generated by Django 4.2.2 on 2023-06-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0005_alter_aboutpage_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='years_exp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
