# Generated by Django 4.2.2 on 2023-06-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0006_alter_aboutpage_years_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_per',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
