# Generated by Django 4.2.2 on 2023-06-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0008_alter_skill_skill_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_per',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
