# Generated by Django 4.2.2 on 2023-06-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0009_alter_skill_skill_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='pro_type',
        ),
    ]
