# Generated by Django 4.2.2 on 2023-06-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0010_remove_projects_date_remove_projects_pro_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_pic',
            field=models.ImageField(blank=True, null=True, upload_to='project pic'),
        ),
    ]
