# Generated by Django 4.1.7 on 2023-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0011_alter_projects_project_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='status',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='phone_no',
            field=models.CharField(max_length=13),
        ),
    ]
