# Generated by Django 4.1.7 on 2023-07-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0013_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=100)),
                ('interest_pic', models.ImageField(blank=True, null=True, upload_to='interest pic')),
            ],
        ),
    ]
