# Generated by Django 4.1.7 on 2023-07-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0016_remove_aboutpage_facebook_remove_aboutpage_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('linkdin', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bannerpage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='services',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
