# Generated by Django 4.1.7 on 2023-07-06 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folioadmin', '0017_socialaccount_remove_aboutpage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
