# Generated by Django 4.1.7 on 2023-07-25 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folioadmin', '0025_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='ending_year',
            field=models.PositiveIntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='starting_year',
            field=models.PositiveIntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, default=True, max_length=500, null=True),
        ),
    ]
