# Generated by Django 4.1.7 on 2023-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0026_education_resume_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.AddField(
            model_name='bannerpage',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
