# Generated by Django 4.1.7 on 2023-07-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0027_remove_education_resume_bannerpage_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ending_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='starting_year',
        ),
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(blank=True, default=True, max_length=15, null=True),
        ),
    ]
