# Generated by Django 4.1.7 on 2023-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folioadmin', '0028_remove_education_ending_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.CharField(blank=True, default=True, max_length=10, null=True),
        ),
    ]
