# Generated by Django 5.1 on 2024-08-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='is_verified',
        ),
    ]
