# Generated by Django 5.1 on 2024-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_userauth_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiletable',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profiletable',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiletable',
            name='linkdin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
